### ISSUE TITLE
Version mismatch - what does it mean and how do I fix it?

### ISSUE THREAD

**Issue by JakeTheSnake3p0** [le0pard/webp-ffi#11]
I've received an error using the sprockets-webp gem that I've traced back to this gem. Whenever I try to encode with Webp I get the error `WebP::EncoderError: Version mismatch`.

Looking at your manual there's a discrepancy in the output by `WebP.decoder_version` and likewise with `WebP.encoder_version`. I get version `0.1.3` and I have installed libwebp at version `0.4.3` as indicated when calling `cwebp -version` in the console. How does this gem discover the executable? I'm guessing there's another version somewhere in my system but I can't find it (`whereis cwebp` only returns one result and it's the `0.4.3` installation).

**Comment by le0pard** [comment]
Hello. This gem doesn't use executable files, like `cwebp`. It builded by using FFI, so it is using source code files of webp library to compile C extension with Ruby bindings. This mean somewhere in your system placed old `.c` and `.h` files for old webp library and library in installation by using env variables for search like `LD_LIBRARY_PATH`, `LD_FLAGS` and `CPATH`. You should search for files, like `webp/decode.h` and `webp/encode.h`, in most cases it installed in system dirs like `/usr`, `/use/local`, etc (for Debian systems using commands `purge` to fully remove some package - with configs and dev files)

**Comment by JakeTheSnake3p0** [comment]
* None of the env variables you mentioned returned anything
* I searched for encode.h and decode.h (using command: `sudo find . -type f -name "encode.h"`) and removed all instances that were in a webp folder
* I followed the instructions [here](http://installion.co.uk/ubuntu/wily/universe/w/webp/uninstall/index.html)

I still get the same result.

**Comment by le0pard** [comment]
I hope after remove webp developer files you also remove gem and install it again, because it also should rebuild. Gem doesn't do something magical in search of this files: https://github.com/le0pard/webp-ffi/blob/master/ext/webp_ffi/Rakefile#L8-L9

**Comment by JakeTheSnake3p0** [comment]
After clearing out my system I ran through the installation process again but no joy.

* Clear all decode.h and encode.h files
* Uninstall web-ffi gem
* Ran `sudo apt-get install libjpeg-dev libpng-dev libtiff-dev libwebp-dev`
* Compiled [latest libwebp](https://developers.google.com/speed/webp/docs/compiling)
* Installed web-ffi gem

Same result.

**Comment by le0pard** [comment]
Emm, `sudo apt-get install libjpeg-dev libpng-dev libtiff-dev libwebp-dev` - does this install old version of webp library? Why you continue installing "libwebp-dev"?

**Comment by JakeTheSnake3p0** [comment]
That command is a [part of your instructions](https://github.com/le0pard/webp-ffi) (under Requirements).

**Comment by le0pard** [comment]
Yes, and it have in bottom such instruction

> Next, you should install libwebp (if you didn't install it by brew in Mac OS or by apt-get in Ubuntu or Debian). Webp library version should be >= 0.3.0. This gem is not support Windows systems.

So, if you old linux system, which doesn't contain Webp >= 0.3.0, you should install it manually, not from package. But for example ubuntu 15.04 have new libwebp in packages, so just need install it from packages.

**Comment by JakeTheSnake3p0** [comment]
Running `sudo apt-get libwebp-dev` fixed the issue. I think your docs should illustrate the distinction more clearly.

In other words, users should be instructed to install libwep compiled locally. If they are uncomfortable doing so you can provide the alternative `apt-get` command to install `libwebp-dev`; but also issue a warning for users that it will install an old version. However the way everything is worded right now gives me the impression I have to do both.

**Comment by le0pard** [comment]
You can submit PR, if docs looks not clear for you.
