### ISSUE TITLE
libpng warning: Application built with libpng-1.2.54 but running with 1.6.34

### ISSUE THREAD

**Issue by btazi** [le0pard/webp-ffi#20]
When I try to convert a png to webp format I get this message:
```
libpng warning: Application built with libpng-1.2.54 but running with 1.6.34
WebP::EncoderError: Cannot read input picture file
```

I'm on ubuntu 18.04, any ideas how to solve this ?

**Comment by le0pard** [comment]
Looks likes you build and running version different for app. You need to fix this issue, like recompile gem with libpng 1.6.34

**Comment by btazi** [comment]
> Looks likes you build and running version different for app. You need to fix this issue, like recompile gem with libpng 1.6.34
Thanks for helping and for this amazing gem @le0pard :blush:
How can I recompile the gem with libpng 1.6.34 ? I'm using it in a Gemfile (rails).

**Comment by le0pard** [comment]
try to uninstall it and after this install by bundler.

**Comment by btazi** [comment]
it worked thanks !
