### ISSUE TITLE
Error when used with GIF file

### ISSUE THREAD

**Issue by pipoblak** [le0pard/webp-ffi#22]
Hi, im recieving this:

WebP::EncoderError (Cannot read input picture file):

when i try to convert a GIF file

**Comment by le0pard** [comment]
@pipoblak thanks. Gem do not support gif, only PNG and JPEG images. For gif conversation you can use separate CLI, which provide webp package https://developers.google.com/speed/webp/docs/gif2webp

**Comment by pipoblak** [comment]
Thanks for the fast response, can you show me how i can use this to create a CarrierWave Image Version ?

**Comment by le0pard** [comment]
@pipoblak make similar processor, like here, but which will run `gif2webp` CLI for your gif files https://github.com/kavu/carrierwave-webp

**Comment by pipoblak** [comment]
got it, sorry for dumb question, but how can i call the CLI from ruby?

**Comment by le0pard** [comment]
https://www.rubyguides.com/2018/12/ruby-system/
