### ISSUE TITLE
Logs while gem install webp-ffi & bundle install - M1 Mac - Apple Silicon

### ISSUE THREAD

**Issue by mehmetmucahitnet** [le0pard/webp-ffi#23]
Building native extensions. This could take a while...
ERROR:  Error installing webp-ffi:
	ERROR: Failed to build gem native extension.

    current directory: /Users/mehmetmucahitnet/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/webp-ffi-0.3.1/ext/webp_ffi
/Users/mehmetmucahitnet/.rbenv/versions/2.6.3/bin/ruby -rrubygems /Users/mehmetmucahitnet/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-13.0.1/exe/rake RUBYARCHDIR\=/Users/mehmetmucahitnet/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/extensions/x86_64-darwin-20/2.6.0/webp-ffi-0.3.1 RUBYLIBDIR\=/Users/mehmetmucahitnet/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/extensions/x86_64-darwin-20/2.6.0/webp-ffi-0.3.1
mkdir -p x86_64-darwin
clang -fexceptions -O -fno-omit-frame-pointer -fno-strict-aliasing -DHAVE_PUTS=1 -DHAVE_WEBPDECODERCONFIG=1 -DHAVE_WEBPGETINFO=1 -DHAVE_STDIO_H=1 -o x86_64-darwin/jpegdec.o -c ./jpegdec.c
In file included from ./jpegdec.c:1:
In file included from ././jpegdec.h:3:
/opt/homebrew/include/webp/encode.h:554:1: error: expected identifier or '('
if c.platform.mac?
^
/opt/homebrew/include/webp/encode.h:555:4: error: invalid preprocessing directive
 # c.cflags << "-arch x86_64"
   ^
/opt/homebrew/include/webp/encode.h:556:4: error: invalid preprocessing directive
 # c.ldflags << "-arch x86_64"
   ^
In file included from ./jpegdec.c:1:
In file included from ././jpegdec.h:4:
/opt/homebrew/include/webp/decode.h:208:5: error: must use 'struct' tag to refer to type 'WebPRGBABuffer'
    WebPRGBABuffer RGBA;
    ^
    struct 
4 errors generated.
rake aborted!
Command failed with status (1): [clang -fexceptions -O -fno-omit-frame-poin...]

Tasks: TOP => default => x86_64-darwin/libwebp_ffi.bundle => x86_64-darwin/jpegdec.o
(See full trace by running task with --trace)

rake failed, exit code 1

Gem files will remain installed in /Users/mehmetmucahitnet/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/webp-ffi-0.3.1 for inspection.
Results logged to /Users/mehmetmucahitnet/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/extensions/x86_64-darwin-20/2.6.0/webp-ffi-0.3.1/gem_make.out

**Comment by le0pard** [comment]
Where is no such lines in 0.3.1 version - https://github.com/le0pard/webp-ffi/commit/671a9c982de479c9122735159292cfd18b69d8d6 (unpack gem and no such lines there)

![image](https://user-images.githubusercontent.com/98444/117452624-a8d77580-af4c-11eb-8416-76e778ccc508.png)

**Comment by mehmetmucahitnet** [comment]
> Where is no such lines in 0.3.1 version - [671a9c9](https://github.com/le0pard/webp-ffi/commit/671a9c982de479c9122735159292cfd18b69d8d6) (unpack gem and no such lines there)
> 
> ![image](https://user-images.githubusercontent.com/98444/117452624-a8d77580-af4c-11eb-8416-76e778ccc508.png)

-----
deleted those codes and tried aganin
----
gem install webp-ffi                                                                                                                                                                                5 ↵
Building native extensions. This could take a while...
ERROR:  Error installing webp-ffi:
	ERROR: Failed to build gem native extension.

    current directory: /Users/mehmetmucahitnet/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/webp-ffi-0.3.1/ext/webp_ffi
/Users/mehmetmucahitnet/.rbenv/versions/2.6.3/bin/ruby -rrubygems /Users/mehmetmucahitnet/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-13.0.1/exe/rake RUBYARCHDIR\=/Users/mehmetmucahitnet/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/extensions/x86_64-darwin-20/2.6.0/webp-ffi-0.3.1 RUBYLIBDIR\=/Users/mehmetmucahitnet/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/extensions/x86_64-darwin-20/2.6.0/webp-ffi-0.3.1
mkdir -p x86_64-darwin
clang -fexceptions -O -fno-omit-frame-pointer -fno-strict-aliasing -DHAVE_PUTS=1 -DHAVE_WEBPDECODERCONFIG=1 -DHAVE_WEBPGETINFO=1 -DHAVE_STDIO_H=1 -o x86_64-darwin/jpegdec.o -c ./jpegdec.c
clang -fexceptions -O -fno-omit-frame-pointer -fno-strict-aliasing -DHAVE_PUTS=1 -DHAVE_WEBPDECODERCONFIG=1 -DHAVE_WEBPGETINFO=1 -DHAVE_STDIO_H=1 -o x86_64-darwin/pngdec.o -c ./pngdec.c
clang -fexceptions -O -fno-omit-frame-pointer -fno-strict-aliasing -DHAVE_PUTS=1 -DHAVE_WEBPDECODERCONFIG=1 -DHAVE_WEBPGETINFO=1 -DHAVE_STDIO_H=1 -o x86_64-darwin/tiffdec.o -c ./tiffdec.c
./tiffdec.c:8:3: warning: 'uint32' is deprecated [-Wdeprecated-declarations]
  uint32 width, height;
  ^
/opt/homebrew/include/tiff.h:84:45: note: 'uint32' has been explicitly marked deprecated here
typedef TIFF_MSC_DEPRECATED uint32_t uint32 TIFF_GCC_DEPRECATED;
                                            ^
/opt/homebrew/include/tiff.h:66:44: note: expanded from macro 'TIFF_GCC_DEPRECATED'
#define TIFF_GCC_DEPRECATED __attribute__((deprecated))
                                           ^
./tiffdec.c:9:3: warning: 'uint32' is deprecated [-Wdeprecated-declarations]
  uint32* raster;
  ^
/opt/homebrew/include/tiff.h:84:45: note: 'uint32' has been explicitly marked deprecated here
typedef TIFF_MSC_DEPRECATED uint32_t uint32 TIFF_GCC_DEPRECATED;
                                            ^
/opt/homebrew/include/tiff.h:66:44: note: expanded from macro 'TIFF_GCC_DEPRECATED'
#define TIFF_GCC_DEPRECATED __attribute__((deprecated))
                                           ^
./tiffdec.c:28:13: warning: 'uint32' is deprecated [-Wdeprecated-declarations]
  raster = (uint32*)_TIFFmalloc(width * height * sizeof(*raster));
            ^
/opt/homebrew/include/tiff.h:84:45: note: 'uint32' has been explicitly marked deprecated here
typedef TIFF_MSC_DEPRECATED uint32_t uint32 TIFF_GCC_DEPRECATED;
                                            ^
/opt/homebrew/include/tiff.h:66:44: note: expanded from macro 'TIFF_GCC_DEPRECATED'
#define TIFF_GCC_DEPRECATED __attribute__((deprecated))
                                           ^
3 warnings generated.
clang -fexceptions -O -fno-omit-frame-pointer -fno-strict-aliasing -DHAVE_PUTS=1 -DHAVE_WEBPDECODERCONFIG=1 -DHAVE_WEBPGETINFO=1 -DHAVE_STDIO_H=1 -o x86_64-darwin/util.o -c ./util.c
clang -fexceptions -O -fno-omit-frame-pointer -fno-strict-aliasing -DHAVE_PUTS=1 -DHAVE_WEBPDECODERCONFIG=1 -DHAVE_WEBPGETINFO=1 -DHAVE_STDIO_H=1 -o x86_64-darwin/webp_ffi.o -c ./webp_ffi.c
clang -bundle -o x86_64-darwin/libwebp_ffi.bundle x86_64-darwin/jpegdec.o x86_64-darwin/pngdec.o x86_64-darwin/tiffdec.o x86_64-darwin/util.o x86_64-darwin/webp_ffi.o -fexceptions -lz -lwebp -lpng -ljpeg -ltiff
ld: library not found for -lwebp
clang: error: linker command failed with exit code 1 (use -v to see invocation)
rake aborted!
Command failed with status (1): [clang -bundle -o x86_64-darwin/libwebp_ffi...]

Tasks: TOP => default => x86_64-darwin/libwebp_ffi.bundle
(See full trace by running task with --trace)

rake failed, exit code 1

Gem files will remain installed in /Users/mehmetmucahitnet/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/webp-ffi-0.3.1 for inspection.
Results logged to /Users/mehmetmucahitnet/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/extensions/x86_64-darwin-20/2.6.0/webp-ffi-0.3.1/gem_make.out

**Comment by le0pard** [comment]
Check why your m1 install gems as `extensions/x86_64-darwin-20`

**Comment by mehmetmucahitnet** [comment]
> Check why your m1 install gems as `extensions/x86_64-darwin-20`

![Ekran Resmi 2021-05-07 16 40 52](https://user-images.githubusercontent.com/31096794/117458553-1686a000-af53-11eb-9027-681f0c79922c.png)

**Comment by le0pard** [comment]
Image is not an answer on my question. Issues with M1 was resolved several month ago - https://github.com/le0pard/webp-ffi/issues/21
